In [36]:
import numpy as np

## 1 Numpy Version

In [3]:
np.__version__

'1.16.5'

## 2 How to create a 1D array

Q. Create a 1D array of numbers from 0 to 9

In [4]:
np.array(np.arange(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 3 How to create boolean array

Q. Create a 3×3 numpy array of all True’s

In [5]:
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## 4 How to extract items that satisfy a given condition from 1D array?

Q. Extract all odd numbers from

In [13]:
arr = np.array(np.arange(10))
arr[np.arange(1,len(arr),2)]

array([1, 3, 5, 7, 9])

## 5 Extract all odd numbers from

Replace all odd numbers in arr with -1

In [20]:
arr[arr%2!=0] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

## 6 How to replace items that satisfy a condition without affecting the original array?

Replace all odd numbers in arr with -1 without changing arr

In [27]:
arr = np.array(np.arange(10))
out = arr[np.where(arr%2!=0)]
print(out)

[1 3 5 7 9]


## 7 How to reshape an array?

Convert a 1D array to a 2D array with 2 rows

In [29]:
arr = np.arange(10)
arr.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## 8 How to stack two arrays vertically?
Stack arrays a and b vertically

In [30]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [31]:
np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## 9 How to stack two arrays horizontally?
Stack the arrays a and b horizontally.

In [32]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [33]:
np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## 10 How to generate custom sequences in numpy without hardcoding?

Create the following pattern without hardcoding. Use only numpy functions and the below input array a

In [34]:
a = np.array([1,2,3])

In [38]:
np.r_[np.repeat(a,3), np.tile(a,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

## 11 How to get the common items between two python numpy arrays?

Get the common items between a and b

In [39]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [40]:
np.intersect1d(a,b)

array([2, 4])

## 12 How to remove from one array those items that exist in another?

From array a remove all items present in array b

In [41]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

In [42]:
np.setdiff1d(a,b)

array([1, 2, 3, 4])

## 13 How to get the positions where elements of two arrays match?

Get the positions where elements of a and b match

In [43]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [45]:
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

## 14 How to extract all numbers between a given range from a numpy array?

Get all items between 5 and 10 from a.

In [46]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

In [52]:
a[np.where((a>5) & (a<=10))]

array([ 6,  9, 10])

In [59]:
def new_sort(a_list, boolean):
    if boolean == True:
        for i in range(len(a_list), 0, -1):
            for j in range(0, i-1):
                if a_list[j] > a_list[j+1]:
                    a_list[j], a_list[j+1] = a_list[j+1], a_list[j]
        return a_list
    elif boolean == False:
        for i in range(len(a_list), 0, -1):
            for j in range(0, i-1):
                if a_list[j] < a_list[j+1]:
                    a_list[j], a_list[j+1] = a_list[j+1], a_list[j]
        return a_list
    
print(new_sort([3,4,5,6,2,7,3], False))

[7, 6, 5, 4, 3, 3, 2]


False