In [6]:
import numpy as np
x = [[1,20,3,400,5], [3,5,7,9,11]]
y = np.array(x)

print(y)
print(y.max())
print(y.min())
print(y.argmax())
print(y.argmin())
print(y.reshape(-1))
print(y.reshape(2,-1))
# print(y.reshape(2,5))

[[  1  20   3 400   5]
 [  3   5   7   9  11]]
400
1
3
0
[  1  20   3 400   5   3   5   7   9  11]
[[  1  20   3 400   5]
 [  3   5   7   9  11]]
[[  1  20   3 400   5]
 [  3   5   7   9  11]]


In [7]:
a = np.array([[1,2,3], [4,5,6]])
b = np.array([[0,0,0], [0,0,0]])
print(a+b)

[[1 2 3]
 [4 5 6]]


In [11]:
# vector identitas penjumlahan dan pengurangan
c = np.zeros((2,3), dtype='int32')
print(c)

[[0 0 0]
 [0 0 0]]


In [15]:
d = np.ones((2,3), dtype='int32')
d

array([[1, 1, 1],
       [1, 1, 1]])

In [19]:
x = np.zeros((3,3), dtype=bool)
print(x)

x = np.ones((3,3), dtype=bool)
print(x)

lain = np.full((3,3), 'Andi')
print(lain)

[[False False False]
 [False False False]
 [False False False]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[['Andi' 'Andi' 'Andi']
 ['Andi' 'Andi' 'Andi']
 ['Andi' 'Andi' 'Andi']]


In [20]:
lain = np.full((3,3), 'Andi')
print(lain)
lain_list = lain.tolist()
print(lain_list)
print(type(lain_list))

[['Andi' 'Andi' 'Andi']
 ['Andi' 'Andi' 'Andi']
 ['Andi' 'Andi' 'Andi']]
[['Andi', 'Andi', 'Andi'], ['Andi', 'Andi', 'Andi'], ['Andi', 'Andi', 'Andi']]
<class 'list'>


In [31]:
x = [0,1,2,3,4]
y = [5,6,7,8,9]
# how to make z = [[0,1,2,3,4], [5,6,7,8,9]]

print('cara 1')
z = []
z.append(x)
z.append(y)
print(z)

print('cara 2')
z = [x, y]
print(z)

print('cara 3')
z = np.array(x+y).reshape(2,-1).tolist()
print(z)

print('cara 4')
a = []
a.extend(x)
a.extend(y)
z = np.array(a).reshape(2,-1).tolist()
print(z)

print('cara 5')
xnp = np.array(x)
ynp = np.array(y)
z = np.concatenate([[xnp],[ynp]], axis=0).tolist()
print(z)

print('cara 6')
z = np.vstack([xnp, ynp]).tolist()
print(z)

cara 1
[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]]
cara 2
[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]]
cara 3
[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]]
cara 4
[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]]
cara 5
[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]]
cara 6
[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]]


In [34]:
a = np.arange(6).reshape(2,-1)
b = np.array([5,6,7,8,9,10]).reshape(2,-1)
d = np.concatenate([a,b], axis=0)
e = np.row_stack((a,b))
f = np.r_[a,b]

print(d)
print(e)
print(f)

[[ 0  1  2]
 [ 3  4  5]
 [ 5  6  7]
 [ 8  9 10]]
[[ 0  1  2]
 [ 3  4  5]
 [ 5  6  7]
 [ 8  9 10]]
[[ 0  1  2]
 [ 3  4  5]
 [ 5  6  7]
 [ 8  9 10]]


In [36]:
npa = np.arange(1,11)
print(npa)

#mengubah angka ganjil jadi 0
npa[npa%2!=0] = 0
print(npa)

[ 1  2  3  4  5  6  7  8  9 10]
[ 0  2  0  4  0  6  0  8  0 10]


In [41]:
x = np.arange(10,20)
print(np.where(x<16)) # menampilkan index value di bawah 16
print(x[np.where(x<16)]) # menampilkan value yang kurang dari 16
print(x[np.arange(5)]) # menampilkan value pada index 0-4 (arange(5))
print(x[np.where((x>14)&(x<18))]) # and operation using ampersand
print(x[np.logical_and(x>14, x<18)]) # and operation using logical_and function

(array([0, 1, 2, 3, 4, 5], dtype=int64),)
[10 11 12 13 14 15]
[10 11 12 13 14]
[15 16 17]
[15 16 17]


## Linear Algabra Determinan

In [42]:
a = np.array([
    [1,2,1],
    [3,3,1],
    [2,1,2]
])
print(np.linalg.det(a))

-6.0


## Linear Algabra Invertion

In [46]:
z = np.array([[3,2], [1,4]])
print(np.linalg.inv(z))

# dot product
print(z@np.linalg.inv(z))
print(z.dot(np.linalg.inv(z)))

[[ 0.4 -0.2]
 [-0.1  0.3]]
[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]


In [49]:
def bigsum(ar):
    a = []
    base = 1000000000
    for i in range(ar):
        base += 1
        a.append(base)
    print(sum(a))

print(type(bigsum(5)))

5000000015
<class 'NoneType'>


In [59]:
ar = '1000000001 1000000002 1000000003 1000000004 1000000005'
ar_split = ar.split(' ')
new_list = []
for a in ar_split:
    new_list.append(int(a))
sum(new_list)

5000000015